### ISSUE TITLE
Fresh Install, Initial Loading Hangs

### ISSUE THREAD

**Issue by davidbwaters** [invu/movieo-app#1] opened 2017-09-10 18:32 UTC
Hi.  I've installed on Windows 10 64-bit (recent insider build) and the app seems to hang at the "Loading, we're loading your movies" screen.  The app becomes unresponsive after a while  Relaunch showed same thing.  Tried running as admin.  It doesn't show any network activity in task manager, either.  Any ideas?

Looking forward to trying the app.

**Comment by invu** [comment] 2017-09-11 14:55
Hello David,

I'm aware of this issue and it's caused by the amount of movies that's being loaded on start-up. The only way around this is to leave the app running for about two minutes and everything will perform as normal. Please let me know if you were unsuccessful to load the movies. This is something that has been on the agenda for a while so I'm hoping to find a work around very soon.

Thank you for letting me know. If you find any other problems please open another issue.

Regards,
NV

**Comment by JourneyOver** [comment] 2017-10-05 18:30
Same issue, just gets stuck on loading and then stops responding.. Left it for over 20 minutes and it never budged at all so ended up force closing it and tried running as admin for another 10 minutes and it just did the same thing..

**Comment by invu** [comment] 2017-10-06 13:02
@JourneyOver We're still working on the loading issues, but it's strange that the app hangs for over 5 minutes, I can load the app within 2 minutes, sometimes not even that. Hopefully the next update should fix this issue, or at least reduce the time.

Regarding not being able to load movies, have you got Windows Media Player installed on your computer? That's the only thing I can think of, unless the files have been removed from the server its being hosted on. Are you able to download them instead of watching? Is this for all the available sources? That may rule out the possibility of the server not being available anymore. If not, then it's most likely the server, which isn't endorsed by me, so PM the movies you were trying to watch and I'll update the sources right away.

**Comment by JourneyOver** [comment] 2017-10-06 21:09
Yea windows media player is installed, as it's usually default installed on any/all windows machine xD (you should be using vlc or something though not windows media player if you are requiring an outside source of a video player)... I've tried downloading them instead of watching them and it seemed like it would download the files (I could never find where the files ended up though, I looked in various places I could think of) and when I went to try and play them through the application it would just throw the same error after a few seconds or so..

when the error first popped up I tried just going through a whole section and every single movie I tried (didn't matter what sources either (most only had 1 source)) threw the same error, it wasn't only specific movies or anything.. so I think the PM would just be every movie that is currently on movieo xD

**Closed** 2017-10-09 14:22 UTC
Labels: enhancement
